name: pr
on:
  pull_request:
    branches:
      - main

env:
  HUGO_VERSION: "0.97.2"

jobs:
  docker:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          # lfs: true

      - name: download hugo extended
        run: |
          curl -O "https://github.com/gohugoio/hugo/releases/download/v${{env.HUGO_VERSION}}/hugo_extended_${{env.HUGO_VERSION}}_Linux-64bit.tar.gz" && \
          mv hugo_extended_${{env.HUGO_VERSION}}_Linux-64bit.tar.gz hugo.tar.gz
          ls
      
      - name: extract hugo tarball
        run: |
          tar -xvf ./hugo.tar.gz -C hugo
          
      - name: symlink hugo
        run: |
          ln -s $PWD/hugo/hugo /usr/local/bin/

      - name: check hugo version
        run: |
          hugo -version

      - name: npm install
        run: |
          npm install && \
          npm install postcss-cli

      - name: hugo build
        run: hugo
