name: pr
on:
  pull_request:
    branches:
      - main

env:
  HUGO_VERSION: "0.97.2"

jobs:
  docker:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          # lfs: true

      - name: download hugo extended
        run: |
          curl -O https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz && \
          tar tvf hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz
      
      - name: extract hugo tarball
        run: |
          tar -xvzf hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz
          
      - name: symlink hugo
        run: |
          ln -s hugo_extended_$HUGO_VERSION_Linux-64bit/hugo /usr/local/bin/

      - name: check hugo version
        run: |
          hugo -version

      - name: npm install
        run: |
          npm install && \
          npm install postcss-cli

      - name: hugo build
        run: hugo
