name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          # lfs: true

      - name: install hugo extended
        run: |
          curl -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION_Linux-64bit.deb && \
          sudo apt install -y ./hugo.deb
        env:
          HUGO_VERSION: "0.97.2"

      - name: npm install
        run: |
          npm install && \
          npm install postcss-cli

      - name: hugo build
        run: hugo
