name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          # lfs: true

      - name: install hugo extended
        run: |
          curl -O https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz
          
          # Verify it is not corrupted
          tar tvf hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz
          
          # extract the tarball
          tar -xvzf hugo_extended_$HUGO_VERSION_Linux-64bit.tar.gz
          
          # Link to bin
          ln -s hugo_extended_$HUGO_VERSION_Linux-64bit/hugo /usr/local/bin/

          # Check Hugo Version
          hugo -version

        env:
          HUGO_VERSION: "0.97.2"

      - name: npm install
        run: |
          npm install && \
          npm install postcss-cli

      - name: hugo build
        run: hugo
